### PR TITLE
Added redirect note.

### PR DESCRIPTION
**Pull request by joerg84**

### CODE REVIEW

**Comment by joerg84** [comment]
Maybe we can even delete this repo?

**Comment by joerg84** [comment]
The important part is just the README redirect if someone ends up at this repo before we get rid of the repo...

**Comment by guenter** [comment]
lgtm, let's just keep the repo here until Netlify has updated their build image and we can build the site automatically. Right now it still gets deployed from the static branch of this repo.

**Comment by joerg84** [comment]
Should we then add the redirect to README (i.e., merge this PR?) @guenter

**Pull request merged**
